### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by mujihuz** [mark-vandenberg/g-hub-mouse-gestures#1]
Hi. 
Is this code updated? I'm total noob and I just wanted to copy paste and use it but it doesn't seem to work.

**Comment by wookiefriseur** [comment]
I'm not using any gesture scripts myself at the moment, but I just tried the script and it works for me. 

What mouse are you using? You might have to skip the default bindings like 4 and 5, because those are Mouse4 and Mouse5 on some mice. I would also recommend to clear the G keys you want to use so their bindings do not interfere.

![grafik](https://user-images.githubusercontent.com/8905319/182478991-2e0e7560-bf35-44d3-a5b5-53bda6cc6b57.png)

**Comment by mark-vandenberg** [comment]
Hi,
The code isn't updated because as far as I can tell it still works great and it hasn't shown any bugs so why change a working piece of script. So it's as updated as need be.

That said, a couple things you need to check is the buttons the script is mapped to, as underlined by @wookiefriseur above. The other thing you need to check is the shortcuts used in System Preferences>Keyboard>Shortcuts
<img width="674" alt="image" src="https://user-images.githubusercontent.com/41389220/182483251-c007dbec-3c85-4e60-884f-ce03ef968e8b.png">

If those are all mapped correctly the script should work and you can check using the debuggingEnabled flag as marked by wookie. If you still encounter problems feel free to respond here with some details about what you checked
